// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package org.spongycastle.asn1.pkcs;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface PKCSObjectIdentifiers
{

    public static final ASN1ObjectIdentifier Yx = new ASN1ObjectIdentifier(abO, "16");
    public static final ASN1ObjectIdentifier aaW = asn1objectidentifier;
    public static final ASN1ObjectIdentifier aaX = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier aaY = new ASN1ObjectIdentifier(aaW, "2");
    public static final ASN1ObjectIdentifier aaZ = new ASN1ObjectIdentifier(aaW, "3");
    public static final ASN1ObjectIdentifier abA = new ASN1ObjectIdentifier(asn1objectidentifier, "2");
    public static final ASN1ObjectIdentifier abB = new ASN1ObjectIdentifier(abz, "4");
    public static final ASN1ObjectIdentifier abC = new ASN1ObjectIdentifier(abz, "5");
    public static final ASN1ObjectIdentifier abD = new ASN1ObjectIdentifier(abz, "7");
    public static final ASN1ObjectIdentifier abE = new ASN1ObjectIdentifier(abz, "8");
    public static final ASN1ObjectIdentifier abF = new ASN1ObjectIdentifier(abz, "9");
    public static final ASN1ObjectIdentifier abG = new ASN1ObjectIdentifier(abz, "10");
    public static final ASN1ObjectIdentifier abH = new ASN1ObjectIdentifier(abz, "11");
    public static final ASN1ObjectIdentifier abI = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1");
    public static final ASN1ObjectIdentifier abJ = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2");
    public static final ASN1ObjectIdentifier abK = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3");
    public static final ASN1ObjectIdentifier abL = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4");
    public static final ASN1ObjectIdentifier abM = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5");
    public static final ASN1ObjectIdentifier abN = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6");
    public static final ASN1ObjectIdentifier abO = asn1objectidentifier;
    public static final ASN1ObjectIdentifier abP = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier abQ = new ASN1ObjectIdentifier(abO, "2");
    public static final ASN1ObjectIdentifier abR = new ASN1ObjectIdentifier(abO, "3");
    public static final ASN1ObjectIdentifier abS = new ASN1ObjectIdentifier(abO, "4");
    public static final ASN1ObjectIdentifier abT = new ASN1ObjectIdentifier(abO, "5");
    public static final ASN1ObjectIdentifier abU = new ASN1ObjectIdentifier(abO, "6");
    public static final ASN1ObjectIdentifier abV = new ASN1ObjectIdentifier(abO, "8");
    public static final ASN1ObjectIdentifier abW = new ASN1ObjectIdentifier(abO, "15");
    public static final ASN1ObjectIdentifier abX = new ASN1ObjectIdentifier(abO, "20");
    public static final ASN1ObjectIdentifier abY = new ASN1ObjectIdentifier(abO, "21");
    public static final ASN1ObjectIdentifier abZ = asn1objectidentifier;
    public static final ASN1ObjectIdentifier aba = new ASN1ObjectIdentifier(aaW, "4");
    public static final ASN1ObjectIdentifier abb = new ASN1ObjectIdentifier(aaW, "5");
    public static final ASN1ObjectIdentifier abc = new ASN1ObjectIdentifier(aaW, "7");
    public static final ASN1ObjectIdentifier abd = new ASN1ObjectIdentifier(aaW, "8");
    public static final ASN1ObjectIdentifier abe = new ASN1ObjectIdentifier(aaW, "9");
    public static final ASN1ObjectIdentifier abf = new ASN1ObjectIdentifier(aaW, "10");
    public static final ASN1ObjectIdentifier abg = new ASN1ObjectIdentifier(aaW, "11");
    public static final ASN1ObjectIdentifier abh = new ASN1ObjectIdentifier(aaW, "12");
    public static final ASN1ObjectIdentifier abi = new ASN1ObjectIdentifier(aaW, "13");
    public static final ASN1ObjectIdentifier abj = new ASN1ObjectIdentifier(aaW, "14");
    public static final ASN1ObjectIdentifier abk = asn1objectidentifier;
    public static final ASN1ObjectIdentifier abl = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier abm = asn1objectidentifier;
    public static final ASN1ObjectIdentifier abn = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier abo = new ASN1ObjectIdentifier(abm, "4");
    public static final ASN1ObjectIdentifier abp = new ASN1ObjectIdentifier(abm, "3");
    public static final ASN1ObjectIdentifier abq = new ASN1ObjectIdentifier(abm, "6");
    public static final ASN1ObjectIdentifier abr = new ASN1ObjectIdentifier(abm, "10");
    public static final ASN1ObjectIdentifier abs = new ASN1ObjectIdentifier(abm, "11");
    public static final ASN1ObjectIdentifier abt = new ASN1ObjectIdentifier(abm, "13");
    public static final ASN1ObjectIdentifier abu = new ASN1ObjectIdentifier(abm, "12");
    public static final ASN1ObjectIdentifier abv = asn1objectidentifier;
    public static final ASN1ObjectIdentifier abw = new ASN1ObjectIdentifier(asn1objectidentifier, "7");
    public static final ASN1ObjectIdentifier abx = new ASN1ObjectIdentifier(abv, "2");
    public static final ASN1ObjectIdentifier aby = new ASN1ObjectIdentifier(abv, "4");
    public static final ASN1ObjectIdentifier abz = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acA = new ASN1ObjectIdentifier(acs, "20");
    public static final ASN1ObjectIdentifier acB = new ASN1ObjectIdentifier(acs, "21");
    public static final ASN1ObjectIdentifier acC = new ASN1ObjectIdentifier(acs, "22");
    public static final ASN1ObjectIdentifier acD = new ASN1ObjectIdentifier(acs, "23");
    public static final ASN1ObjectIdentifier acE = new ASN1ObjectIdentifier(acs, "24");
    public static final ASN1ObjectIdentifier acF = new ASN1ObjectIdentifier(acs, "25");
    public static final ASN1ObjectIdentifier acG = new ASN1ObjectIdentifier(acs, "26");
    public static final ASN1ObjectIdentifier acH = new ASN1ObjectIdentifier(acs, "27");
    public static final ASN1ObjectIdentifier acI = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acJ = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acK = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier acL = new ASN1ObjectIdentifier(acJ, "2");
    public static final ASN1ObjectIdentifier acM = new ASN1ObjectIdentifier(acJ, "3");
    public static final ASN1ObjectIdentifier acN = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acO = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier acP = new ASN1ObjectIdentifier(acN, "2");
    public static final ASN1ObjectIdentifier acQ = new ASN1ObjectIdentifier(acN, "3");
    public static final ASN1ObjectIdentifier acR = new ASN1ObjectIdentifier(acN, "4");
    public static final ASN1ObjectIdentifier acS = new ASN1ObjectIdentifier(acN, "5");
    public static final ASN1ObjectIdentifier acT = new ASN1ObjectIdentifier(acN, "6");
    public static final ASN1ObjectIdentifier acU = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
    public static final ASN1ObjectIdentifier acV = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
    public static final ASN1ObjectIdentifier aca = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier acb = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acc = new ASN1ObjectIdentifier(abO, "15.1");
    public static final ASN1ObjectIdentifier acd = new ASN1ObjectIdentifier(abO, "15.2");
    public static final ASN1ObjectIdentifier ace = new ASN1ObjectIdentifier(abO, "15.3");
    public static final ASN1ObjectIdentifier acf = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acg = new ASN1ObjectIdentifier(asn1objectidentifier, "2");
    public static final ASN1ObjectIdentifier ach = new ASN1ObjectIdentifier(acf, "9");
    public static final ASN1ObjectIdentifier aci = new ASN1ObjectIdentifier(acf, "23");
    public static final ASN1ObjectIdentifier acj = new ASN1ObjectIdentifier(acf, "31");
    public static final ASN1ObjectIdentifier ack = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acl = asn1objectidentifier;
    public static final ASN1ObjectIdentifier acm = new ASN1ObjectIdentifier(asn1objectidentifier, "1");
    public static final ASN1ObjectIdentifier acn = new ASN1ObjectIdentifier(acl, "2");
    public static final ASN1ObjectIdentifier aco = new ASN1ObjectIdentifier(acl, "3");
    public static final ASN1ObjectIdentifier acp = new ASN1ObjectIdentifier(acl, "4");
    public static final ASN1ObjectIdentifier acq = new ASN1ObjectIdentifier(acl, "5");
    public static final ASN1ObjectIdentifier acr = new ASN1ObjectIdentifier(acl, "6");
    public static final ASN1ObjectIdentifier acs = asn1objectidentifier;
    public static final ASN1ObjectIdentifier act = new ASN1ObjectIdentifier(acs, "4");
    public static final ASN1ObjectIdentifier acu = new ASN1ObjectIdentifier(acs, "11");
    public static final ASN1ObjectIdentifier acv = new ASN1ObjectIdentifier(acs, "15");
    public static final ASN1ObjectIdentifier acw = new ASN1ObjectIdentifier(acs, "16");
    public static final ASN1ObjectIdentifier acx = new ASN1ObjectIdentifier(acs, "17");
    public static final ASN1ObjectIdentifier acy = new ASN1ObjectIdentifier(acs, "18");
    public static final ASN1ObjectIdentifier acz = new ASN1ObjectIdentifier(acs, "19");

    
    {
        ASN1ObjectIdentifier asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        new ASN1ObjectIdentifier(aaW, "6");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.3");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.2");
        new ASN1ObjectIdentifier("1.2.840.113549.1.7");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        new ASN1ObjectIdentifier(abO, "7");
        new ASN1ObjectIdentifier(abO, "9");
        new ASN1ObjectIdentifier(abO, "13");
        new ASN1ObjectIdentifier(abO, "14");
        new ASN1ObjectIdentifier(abO, "22.1");
        asn1objectidentifier = new ASN1ObjectIdentifier(abO, "22");
        new ASN1ObjectIdentifier(abZ, "2");
        asn1objectidentifier = new ASN1ObjectIdentifier(abO, "23");
        new ASN1ObjectIdentifier(asn1objectidentifier, "1");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        new ASN1ObjectIdentifier(acf, "4");
        asn1objectidentifier = new ASN1ObjectIdentifier(Yx, "3");
        new ASN1ObjectIdentifier(asn1objectidentifier, "9");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        new ASN1ObjectIdentifier(asn1objectidentifier, "1");
        new ASN1ObjectIdentifier(acs, "5");
        new ASN1ObjectIdentifier(acs, "10");
        new ASN1ObjectIdentifier(acs, "12");
        new ASN1ObjectIdentifier(acs, "47");
        new ASN1ObjectIdentifier(acs, "7");
        new ASN1ObjectIdentifier(acs, "14");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        asn1objectidentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        asn1objectidentifier = new ASN1ObjectIdentifier(asn1objectidentifier, "10.1");
        new ASN1ObjectIdentifier(acJ, "4");
        new ASN1ObjectIdentifier(acJ, "5");
        new ASN1ObjectIdentifier(acJ, "6");
        asn1objectidentifier = new ASN1ObjectIdentifier(acI, "1");
        new ASN1ObjectIdentifier(acN, "6");
    }
}
