// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.digits.sdk.android;

import android.text.TextUtils;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

// Referenced classes of package com.digits.sdk.android:
//            SimManager, PhoneNumber

class PhoneNumberUtils
{

    private static final String DEFAULT_COUNTRY_CODE = "1";
    private static final String DEFAULT_COUNTRY_ISO = "US";
    private static final int MAX_COUNTRIES = 291;
    private static final int MAX_COUNTRY_CODES = 286;
    private final SimManager simManager;

    PhoneNumberUtils(SimManager simmanager)
    {
        simManager = simmanager;
    }

    private String countryCodeForPhoneNumber(Map map, String s)
    {
        for (int i = 3; i > 0; i--)
        {
            String s1 = s.substring(1, i);
            if (map.containsKey(Integer.valueOf(s1)))
            {
                return s1;
            }
        }

        return "1";
    }

    private String countryIsoForCountryCode(Map map, String s)
    {
        map = (List)map.get(Integer.valueOf(s));
        if (map != null)
        {
            return (String)map.get(0);
        } else
        {
            return "US";
        }
    }

    private Map createCountryCodeByIsoMap()
    {
        HashMap hashmap = new HashMap(291);
        hashmap.put("AF", Integer.valueOf(93));
        hashmap.put("AX", Integer.valueOf(358));
        hashmap.put("AL", Integer.valueOf(355));
        hashmap.put("DZ", Integer.valueOf(213));
        hashmap.put("AS", Integer.valueOf(1));
        hashmap.put("AD", Integer.valueOf(376));
        hashmap.put("AO", Integer.valueOf(244));
        hashmap.put("AI", Integer.valueOf(1));
        hashmap.put("AG", Integer.valueOf(1));
        hashmap.put("AR", Integer.valueOf(54));
        hashmap.put("AM", Integer.valueOf(374));
        hashmap.put("AW", Integer.valueOf(297));
        hashmap.put("AC", Integer.valueOf(247));
        hashmap.put("AU", Integer.valueOf(61));
        hashmap.put("AT", Integer.valueOf(43));
        hashmap.put("AZ", Integer.valueOf(994));
        hashmap.put("BS", Integer.valueOf(1));
        hashmap.put("BH", Integer.valueOf(973));
        hashmap.put("BD", Integer.valueOf(880));
        hashmap.put("BB", Integer.valueOf(1));
        hashmap.put("BY", Integer.valueOf(375));
        hashmap.put("BE", Integer.valueOf(32));
        hashmap.put("BZ", Integer.valueOf(501));
        hashmap.put("BJ", Integer.valueOf(229));
        hashmap.put("BM", Integer.valueOf(1));
        hashmap.put("BT", Integer.valueOf(975));
        hashmap.put("BO", Integer.valueOf(591));
        hashmap.put("BA", Integer.valueOf(387));
        hashmap.put("BW", Integer.valueOf(267));
        hashmap.put("BR", Integer.valueOf(55));
        hashmap.put("IO", Integer.valueOf(246));
        hashmap.put("VG", Integer.valueOf(1));
        hashmap.put("BN", Integer.valueOf(673));
        hashmap.put("BG", Integer.valueOf(359));
        hashmap.put("BF", Integer.valueOf(226));
        hashmap.put("BI", Integer.valueOf(257));
        hashmap.put("KH", Integer.valueOf(855));
        hashmap.put("CM", Integer.valueOf(237));
        hashmap.put("CA", Integer.valueOf(1));
        hashmap.put("CV", Integer.valueOf(238));
        hashmap.put("BQ", Integer.valueOf(599));
        hashmap.put("KY", Integer.valueOf(1));
        hashmap.put("CF", Integer.valueOf(236));
        hashmap.put("TD", Integer.valueOf(235));
        hashmap.put("CL", Integer.valueOf(56));
        hashmap.put("CN", Integer.valueOf(86));
        hashmap.put("CX", Integer.valueOf(61));
        hashmap.put("CC", Integer.valueOf(61));
        hashmap.put("CO", Integer.valueOf(57));
        hashmap.put("KM", Integer.valueOf(269));
        hashmap.put("CD", Integer.valueOf(243));
        hashmap.put("CG", Integer.valueOf(242));
        hashmap.put("CK", Integer.valueOf(682));
        hashmap.put("CR", Integer.valueOf(506));
        hashmap.put("CI", Integer.valueOf(225));
        hashmap.put("HR", Integer.valueOf(385));
        hashmap.put("CU", Integer.valueOf(53));
        hashmap.put("CW", Integer.valueOf(599));
        hashmap.put("CY", Integer.valueOf(357));
        hashmap.put("CZ", Integer.valueOf(420));
        hashmap.put("DK", Integer.valueOf(45));
        hashmap.put("DJ", Integer.valueOf(253));
        hashmap.put("DM", Integer.valueOf(1));
        hashmap.put("DO", Integer.valueOf(1));
        hashmap.put("TL", Integer.valueOf(670));
        hashmap.put("EC", Integer.valueOf(593));
        hashmap.put("EG", Integer.valueOf(20));
        hashmap.put("SV", Integer.valueOf(503));
        hashmap.put("GQ", Integer.valueOf(240));
        hashmap.put("ER", Integer.valueOf(291));
        hashmap.put("EE", Integer.valueOf(372));
        hashmap.put("ET", Integer.valueOf(251));
        hashmap.put("FK", Integer.valueOf(500));
        hashmap.put("FO", Integer.valueOf(298));
        hashmap.put("FJ", Integer.valueOf(679));
        hashmap.put("FI", Integer.valueOf(358));
        hashmap.put("FR", Integer.valueOf(33));
        hashmap.put("GF", Integer.valueOf(594));
        hashmap.put("PF", Integer.valueOf(689));
        hashmap.put("GA", Integer.valueOf(241));
        hashmap.put("GM", Integer.valueOf(220));
        hashmap.put("GE", Integer.valueOf(995));
        hashmap.put("DE", Integer.valueOf(49));
        hashmap.put("GH", Integer.valueOf(233));
        hashmap.put("GI", Integer.valueOf(350));
        hashmap.put("GR", Integer.valueOf(30));
        hashmap.put("GL", Integer.valueOf(299));
        hashmap.put("GD", Integer.valueOf(1));
        hashmap.put("GP", Integer.valueOf(590));
        hashmap.put("GU", Integer.valueOf(1));
        hashmap.put("GT", Integer.valueOf(502));
        hashmap.put("GG", Integer.valueOf(44));
        hashmap.put("GN", Integer.valueOf(224));
        hashmap.put("GW", Integer.valueOf(245));
        hashmap.put("GY", Integer.valueOf(592));
        hashmap.put("HT", Integer.valueOf(509));
        hashmap.put("HM", Integer.valueOf(672));
        hashmap.put("HN", Integer.valueOf(504));
        hashmap.put("HK", Integer.valueOf(852));
        hashmap.put("HU", Integer.valueOf(36));
        hashmap.put("IS", Integer.valueOf(354));
        hashmap.put("IN", Integer.valueOf(91));
        hashmap.put("ID", Integer.valueOf(62));
        hashmap.put("IR", Integer.valueOf(98));
        hashmap.put("IQ", Integer.valueOf(964));
        hashmap.put("IE", Integer.valueOf(353));
        hashmap.put("IM", Integer.valueOf(44));
        hashmap.put("IL", Integer.valueOf(972));
        hashmap.put("IT", Integer.valueOf(39));
        hashmap.put("JM", Integer.valueOf(1));
        hashmap.put("JP", Integer.valueOf(81));
        hashmap.put("JE", Integer.valueOf(44));
        hashmap.put("JO", Integer.valueOf(962));
        hashmap.put("KZ", Integer.valueOf(7));
        hashmap.put("KE", Integer.valueOf(254));
        hashmap.put("KI", Integer.valueOf(686));
        hashmap.put("XK", Integer.valueOf(381));
        hashmap.put("KW", Integer.valueOf(965));
        hashmap.put("KG", Integer.valueOf(996));
        hashmap.put("LA", Integer.valueOf(856));
        hashmap.put("LV", Integer.valueOf(371));
        hashmap.put("LB", Integer.valueOf(961));
        hashmap.put("LS", Integer.valueOf(266));
        hashmap.put("LR", Integer.valueOf(231));
        hashmap.put("LY", Integer.valueOf(218));
        hashmap.put("LI", Integer.valueOf(423));
        hashmap.put("LT", Integer.valueOf(370));
        hashmap.put("LU", Integer.valueOf(352));
        hashmap.put("MO", Integer.valueOf(853));
        hashmap.put("MK", Integer.valueOf(389));
        hashmap.put("MG", Integer.valueOf(261));
        hashmap.put("MW", Integer.valueOf(265));
        hashmap.put("MY", Integer.valueOf(60));
        hashmap.put("MV", Integer.valueOf(960));
        hashmap.put("ML", Integer.valueOf(223));
        hashmap.put("MT", Integer.valueOf(356));
        hashmap.put("MH", Integer.valueOf(692));
        hashmap.put("MQ", Integer.valueOf(596));
        hashmap.put("MR", Integer.valueOf(222));
        hashmap.put("MU", Integer.valueOf(230));
        hashmap.put("YT", Integer.valueOf(262));
        hashmap.put("MX", Integer.valueOf(52));
        hashmap.put("FM", Integer.valueOf(691));
        hashmap.put("MD", Integer.valueOf(373));
        hashmap.put("MC", Integer.valueOf(377));
        hashmap.put("MN", Integer.valueOf(976));
        hashmap.put("ME", Integer.valueOf(382));
        hashmap.put("MS", Integer.valueOf(1));
        hashmap.put("MA", Integer.valueOf(212));
        hashmap.put("MZ", Integer.valueOf(258));
        hashmap.put("MM", Integer.valueOf(95));
        hashmap.put("NA", Integer.valueOf(264));
        hashmap.put("NR", Integer.valueOf(674));
        hashmap.put("NP", Integer.valueOf(977));
        hashmap.put("NL", Integer.valueOf(31));
        hashmap.put("NC", Integer.valueOf(687));
        hashmap.put("NZ", Integer.valueOf(64));
        hashmap.put("NI", Integer.valueOf(505));
        hashmap.put("NE", Integer.valueOf(227));
        hashmap.put("NG", Integer.valueOf(234));
        hashmap.put("NU", Integer.valueOf(683));
        hashmap.put("NF", Integer.valueOf(672));
        hashmap.put("KP", Integer.valueOf(850));
        hashmap.put("MP", Integer.valueOf(1));
        hashmap.put("NO", Integer.valueOf(47));
        hashmap.put("OM", Integer.valueOf(968));
        hashmap.put("PK", Integer.valueOf(92));
        hashmap.put("PW", Integer.valueOf(680));
        hashmap.put("PS", Integer.valueOf(970));
        hashmap.put("PA", Integer.valueOf(507));
        hashmap.put("PG", Integer.valueOf(675));
        hashmap.put("PY", Integer.valueOf(595));
        hashmap.put("PE", Integer.valueOf(51));
        hashmap.put("PH", Integer.valueOf(63));
        hashmap.put("PL", Integer.valueOf(48));
        hashmap.put("PT", Integer.valueOf(351));
        hashmap.put("PR", Integer.valueOf(1));
        hashmap.put("QA", Integer.valueOf(974));
        hashmap.put("RE", Integer.valueOf(262));
        hashmap.put("RO", Integer.valueOf(40));
        hashmap.put("RU", Integer.valueOf(7));
        hashmap.put("RW", Integer.valueOf(250));
        hashmap.put("BL", Integer.valueOf(590));
        hashmap.put("SH", Integer.valueOf(290));
        hashmap.put("KN", Integer.valueOf(1));
        hashmap.put("LC", Integer.valueOf(1));
        hashmap.put("MF", Integer.valueOf(590));
        hashmap.put("PM", Integer.valueOf(508));
        hashmap.put("VC", Integer.valueOf(1));
        hashmap.put("WS", Integer.valueOf(685));
        hashmap.put("SM", Integer.valueOf(378));
        hashmap.put("ST", Integer.valueOf(239));
        hashmap.put("SA", Integer.valueOf(966));
        hashmap.put("SN", Integer.valueOf(221));
        hashmap.put("RS", Integer.valueOf(381));
        hashmap.put("SC", Integer.valueOf(248));
        hashmap.put("SL", Integer.valueOf(232));
        hashmap.put("SG", Integer.valueOf(65));
        hashmap.put("SX", Integer.valueOf(1));
        hashmap.put("SK", Integer.valueOf(421));
        hashmap.put("SI", Integer.valueOf(386));
        hashmap.put("SB", Integer.valueOf(677));
        hashmap.put("SO", Integer.valueOf(252));
        hashmap.put("ZA", Integer.valueOf(27));
        hashmap.put("GS", Integer.valueOf(500));
        hashmap.put("KR", Integer.valueOf(82));
        hashmap.put("SS", Integer.valueOf(211));
        hashmap.put("ES", Integer.valueOf(34));
        hashmap.put("LK", Integer.valueOf(94));
        hashmap.put("SD", Integer.valueOf(249));
        hashmap.put("SR", Integer.valueOf(597));
        hashmap.put("SJ", Integer.valueOf(47));
        hashmap.put("SZ", Integer.valueOf(268));
        hashmap.put("SE", Integer.valueOf(46));
        hashmap.put("CH", Integer.valueOf(41));
        hashmap.put("SY", Integer.valueOf(963));
        hashmap.put("TW", Integer.valueOf(886));
        hashmap.put("TJ", Integer.valueOf(992));
        hashmap.put("TZ", Integer.valueOf(255));
        hashmap.put("TH", Integer.valueOf(66));
        hashmap.put("TG", Integer.valueOf(228));
        hashmap.put("TK", Integer.valueOf(690));
        hashmap.put("TO", Integer.valueOf(676));
        hashmap.put("TT", Integer.valueOf(1));
        hashmap.put("TN", Integer.valueOf(216));
        hashmap.put("TR", Integer.valueOf(90));
        hashmap.put("TM", Integer.valueOf(993));
        hashmap.put("TC", Integer.valueOf(1));
        hashmap.put("TV", Integer.valueOf(688));
        hashmap.put("VI", Integer.valueOf(1));
        hashmap.put("UG", Integer.valueOf(256));
        hashmap.put("UA", Integer.valueOf(380));
        hashmap.put("AE", Integer.valueOf(971));
        hashmap.put("GB", Integer.valueOf(44));
        hashmap.put("US", Integer.valueOf(1));
        hashmap.put("UY", Integer.valueOf(598));
        hashmap.put("UZ", Integer.valueOf(998));
        hashmap.put("VU", Integer.valueOf(678));
        hashmap.put("VA", Integer.valueOf(379));
        hashmap.put("VE", Integer.valueOf(58));
        hashmap.put("VN", Integer.valueOf(84));
        hashmap.put("WF", Integer.valueOf(681));
        hashmap.put("EH", Integer.valueOf(212));
        hashmap.put("YE", Integer.valueOf(967));
        hashmap.put("ZM", Integer.valueOf(260));
        hashmap.put("ZW", Integer.valueOf(263));
        return hashmap;
    }

    private Map createCountryCodeToRegionCodeMap()
    {
        HashMap hashmap = new HashMap(286);
        ArrayList arraylist = new ArrayList(25);
        arraylist.add("US");
        arraylist.add("AG");
        arraylist.add("AI");
        arraylist.add("AS");
        arraylist.add("BB");
        arraylist.add("BM");
        arraylist.add("BS");
        arraylist.add("CA");
        arraylist.add("DM");
        arraylist.add("DO");
        arraylist.add("GD");
        arraylist.add("GU");
        arraylist.add("JM");
        arraylist.add("KN");
        arraylist.add("KY");
        arraylist.add("LC");
        arraylist.add("MP");
        arraylist.add("MS");
        arraylist.add("PR");
        arraylist.add("SX");
        arraylist.add("TC");
        arraylist.add("TT");
        arraylist.add("VC");
        arraylist.add("VG");
        arraylist.add("VI");
        hashmap.put(Integer.valueOf(1), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("RU");
        arraylist.add("KZ");
        hashmap.put(Integer.valueOf(7), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EG");
        hashmap.put(Integer.valueOf(20), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZA");
        hashmap.put(Integer.valueOf(27), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GR");
        hashmap.put(Integer.valueOf(30), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NL");
        hashmap.put(Integer.valueOf(31), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BE");
        hashmap.put(Integer.valueOf(32), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FR");
        hashmap.put(Integer.valueOf(33), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ES");
        hashmap.put(Integer.valueOf(34), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HU");
        hashmap.put(Integer.valueOf(36), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IT");
        hashmap.put(Integer.valueOf(39), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RO");
        hashmap.put(Integer.valueOf(40), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CH");
        hashmap.put(Integer.valueOf(41), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AT");
        hashmap.put(Integer.valueOf(43), arraylist);
        arraylist = new ArrayList(4);
        arraylist.add("GB");
        arraylist.add("GG");
        arraylist.add("IM");
        arraylist.add("JE");
        hashmap.put(Integer.valueOf(44), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DK");
        hashmap.put(Integer.valueOf(45), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SE");
        hashmap.put(Integer.valueOf(46), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("NO");
        arraylist.add("SJ");
        hashmap.put(Integer.valueOf(47), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PL");
        hashmap.put(Integer.valueOf(48), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DE");
        hashmap.put(Integer.valueOf(49), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PE");
        hashmap.put(Integer.valueOf(51), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MX");
        hashmap.put(Integer.valueOf(52), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CU");
        hashmap.put(Integer.valueOf(53), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AR");
        hashmap.put(Integer.valueOf(54), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BR");
        hashmap.put(Integer.valueOf(55), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CL");
        hashmap.put(Integer.valueOf(56), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CO");
        hashmap.put(Integer.valueOf(57), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VE");
        hashmap.put(Integer.valueOf(58), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MY");
        hashmap.put(Integer.valueOf(60), arraylist);
        arraylist = new ArrayList(3);
        arraylist.add("AU");
        arraylist.add("CC");
        arraylist.add("CX");
        hashmap.put(Integer.valueOf(61), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ID");
        hashmap.put(Integer.valueOf(62), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PH");
        hashmap.put(Integer.valueOf(63), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NZ");
        hashmap.put(Integer.valueOf(64), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SG");
        hashmap.put(Integer.valueOf(65), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TH");
        hashmap.put(Integer.valueOf(66), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("JP");
        hashmap.put(Integer.valueOf(81), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KR");
        hashmap.put(Integer.valueOf(82), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VN");
        hashmap.put(Integer.valueOf(84), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CN");
        hashmap.put(Integer.valueOf(86), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TR");
        hashmap.put(Integer.valueOf(90), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IN");
        hashmap.put(Integer.valueOf(91), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PK");
        hashmap.put(Integer.valueOf(92), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AF");
        hashmap.put(Integer.valueOf(93), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LK");
        hashmap.put(Integer.valueOf(94), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MM");
        hashmap.put(Integer.valueOf(95), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IR");
        hashmap.put(Integer.valueOf(98), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SS");
        hashmap.put(Integer.valueOf(211), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("MA");
        arraylist.add("EH");
        hashmap.put(Integer.valueOf(212), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DZ");
        hashmap.put(Integer.valueOf(213), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TN");
        hashmap.put(Integer.valueOf(216), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LY");
        hashmap.put(Integer.valueOf(218), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GM");
        hashmap.put(Integer.valueOf(220), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SN");
        hashmap.put(Integer.valueOf(221), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MR");
        hashmap.put(Integer.valueOf(222), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ML");
        hashmap.put(Integer.valueOf(223), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GN");
        hashmap.put(Integer.valueOf(224), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CI");
        hashmap.put(Integer.valueOf(225), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BF");
        hashmap.put(Integer.valueOf(226), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NE");
        hashmap.put(Integer.valueOf(227), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TG");
        hashmap.put(Integer.valueOf(228), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BJ");
        hashmap.put(Integer.valueOf(229), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MU");
        hashmap.put(Integer.valueOf(230), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LR");
        hashmap.put(Integer.valueOf(231), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SL");
        hashmap.put(Integer.valueOf(232), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GH");
        hashmap.put(Integer.valueOf(233), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NG");
        hashmap.put(Integer.valueOf(234), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TD");
        hashmap.put(Integer.valueOf(235), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CF");
        hashmap.put(Integer.valueOf(236), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CM");
        hashmap.put(Integer.valueOf(237), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CV");
        hashmap.put(Integer.valueOf(238), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ST");
        hashmap.put(Integer.valueOf(239), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GQ");
        hashmap.put(Integer.valueOf(240), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GA");
        hashmap.put(Integer.valueOf(241), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CG");
        hashmap.put(Integer.valueOf(242), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CD");
        hashmap.put(Integer.valueOf(243), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AO");
        hashmap.put(Integer.valueOf(244), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GW");
        hashmap.put(Integer.valueOf(245), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IO");
        hashmap.put(Integer.valueOf(246), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AC");
        hashmap.put(Integer.valueOf(247), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SC");
        hashmap.put(Integer.valueOf(248), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SD");
        hashmap.put(Integer.valueOf(249), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RW");
        hashmap.put(Integer.valueOf(250), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ET");
        hashmap.put(Integer.valueOf(251), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SO");
        hashmap.put(Integer.valueOf(252), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DJ");
        hashmap.put(Integer.valueOf(253), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KE");
        hashmap.put(Integer.valueOf(254), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TZ");
        hashmap.put(Integer.valueOf(255), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UG");
        hashmap.put(Integer.valueOf(256), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BI");
        hashmap.put(Integer.valueOf(257), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MZ");
        hashmap.put(Integer.valueOf(258), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZM");
        hashmap.put(Integer.valueOf(260), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MG");
        hashmap.put(Integer.valueOf(261), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("RE");
        arraylist.add("YT");
        hashmap.put(Integer.valueOf(262), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZW");
        hashmap.put(Integer.valueOf(263), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NA");
        hashmap.put(Integer.valueOf(264), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MW");
        hashmap.put(Integer.valueOf(265), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LS");
        hashmap.put(Integer.valueOf(266), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BW");
        hashmap.put(Integer.valueOf(267), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SZ");
        hashmap.put(Integer.valueOf(268), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KM");
        hashmap.put(Integer.valueOf(269), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("SH");
        arraylist.add("TA");
        hashmap.put(Integer.valueOf(290), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ER");
        hashmap.put(Integer.valueOf(291), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AW");
        hashmap.put(Integer.valueOf(297), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FO");
        hashmap.put(Integer.valueOf(298), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GL");
        hashmap.put(Integer.valueOf(299), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GI");
        hashmap.put(Integer.valueOf(350), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PT");
        hashmap.put(Integer.valueOf(351), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LU");
        hashmap.put(Integer.valueOf(352), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IE");
        hashmap.put(Integer.valueOf(353), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IS");
        hashmap.put(Integer.valueOf(354), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AL");
        hashmap.put(Integer.valueOf(355), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MT");
        hashmap.put(Integer.valueOf(356), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CY");
        hashmap.put(Integer.valueOf(357), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("FI");
        arraylist.add("AX");
        hashmap.put(Integer.valueOf(358), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BG");
        hashmap.put(Integer.valueOf(359), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LT");
        hashmap.put(Integer.valueOf(370), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LV");
        hashmap.put(Integer.valueOf(371), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EE");
        hashmap.put(Integer.valueOf(372), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MD");
        hashmap.put(Integer.valueOf(373), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AM");
        hashmap.put(Integer.valueOf(374), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BY");
        hashmap.put(Integer.valueOf(375), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AD");
        hashmap.put(Integer.valueOf(376), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MC");
        hashmap.put(Integer.valueOf(377), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SM");
        hashmap.put(Integer.valueOf(378), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VA");
        hashmap.put(Integer.valueOf(379), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UA");
        hashmap.put(Integer.valueOf(380), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RS");
        hashmap.put(Integer.valueOf(381), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ME");
        hashmap.put(Integer.valueOf(382), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HR");
        hashmap.put(Integer.valueOf(385), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SI");
        hashmap.put(Integer.valueOf(386), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BA");
        hashmap.put(Integer.valueOf(387), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MK");
        hashmap.put(Integer.valueOf(389), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CZ");
        hashmap.put(Integer.valueOf(420), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SK");
        hashmap.put(Integer.valueOf(421), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LI");
        hashmap.put(Integer.valueOf(423), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FK");
        hashmap.put(Integer.valueOf(500), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BZ");
        hashmap.put(Integer.valueOf(501), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GT");
        hashmap.put(Integer.valueOf(502), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SV");
        hashmap.put(Integer.valueOf(503), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HN");
        hashmap.put(Integer.valueOf(504), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NI");
        hashmap.put(Integer.valueOf(505), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CR");
        hashmap.put(Integer.valueOf(506), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PA");
        hashmap.put(Integer.valueOf(507), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PM");
        hashmap.put(Integer.valueOf(508), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HT");
        hashmap.put(Integer.valueOf(509), arraylist);
        arraylist = new ArrayList(3);
        arraylist.add("GP");
        arraylist.add("BL");
        arraylist.add("MF");
        hashmap.put(Integer.valueOf(590), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BO");
        hashmap.put(Integer.valueOf(591), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GY");
        hashmap.put(Integer.valueOf(592), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EC");
        hashmap.put(Integer.valueOf(593), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GF");
        hashmap.put(Integer.valueOf(594), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PY");
        hashmap.put(Integer.valueOf(595), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MQ");
        hashmap.put(Integer.valueOf(596), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SR");
        hashmap.put(Integer.valueOf(597), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UY");
        hashmap.put(Integer.valueOf(598), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("CW");
        arraylist.add("BQ");
        hashmap.put(Integer.valueOf(599), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TL");
        hashmap.put(Integer.valueOf(670), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NF");
        hashmap.put(Integer.valueOf(672), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BN");
        hashmap.put(Integer.valueOf(673), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NR");
        hashmap.put(Integer.valueOf(674), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PG");
        hashmap.put(Integer.valueOf(675), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TO");
        hashmap.put(Integer.valueOf(676), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SB");
        hashmap.put(Integer.valueOf(677), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VU");
        hashmap.put(Integer.valueOf(678), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FJ");
        hashmap.put(Integer.valueOf(679), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PW");
        hashmap.put(Integer.valueOf(680), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("WF");
        hashmap.put(Integer.valueOf(681), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CK");
        hashmap.put(Integer.valueOf(682), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NU");
        hashmap.put(Integer.valueOf(683), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("WS");
        hashmap.put(Integer.valueOf(685), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KI");
        hashmap.put(Integer.valueOf(686), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NC");
        hashmap.put(Integer.valueOf(687), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TV");
        hashmap.put(Integer.valueOf(688), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PF");
        hashmap.put(Integer.valueOf(689), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TK");
        hashmap.put(Integer.valueOf(690), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FM");
        hashmap.put(Integer.valueOf(691), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MH");
        hashmap.put(Integer.valueOf(692), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(800), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(808), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KP");
        hashmap.put(Integer.valueOf(850), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HK");
        hashmap.put(Integer.valueOf(852), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MO");
        hashmap.put(Integer.valueOf(853), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KH");
        hashmap.put(Integer.valueOf(855), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LA");
        hashmap.put(Integer.valueOf(856), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(870), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(878), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BD");
        hashmap.put(Integer.valueOf(880), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(881), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(882), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(883), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TW");
        hashmap.put(Integer.valueOf(886), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(888), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MV");
        hashmap.put(Integer.valueOf(960), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LB");
        hashmap.put(Integer.valueOf(961), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("JO");
        hashmap.put(Integer.valueOf(962), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SY");
        hashmap.put(Integer.valueOf(963), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IQ");
        hashmap.put(Integer.valueOf(964), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KW");
        hashmap.put(Integer.valueOf(965), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SA");
        hashmap.put(Integer.valueOf(966), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("YE");
        hashmap.put(Integer.valueOf(967), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("OM");
        hashmap.put(Integer.valueOf(968), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PS");
        hashmap.put(Integer.valueOf(970), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AE");
        hashmap.put(Integer.valueOf(971), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IL");
        hashmap.put(Integer.valueOf(972), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BH");
        hashmap.put(Integer.valueOf(973), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("QA");
        hashmap.put(Integer.valueOf(974), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BT");
        hashmap.put(Integer.valueOf(975), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MN");
        hashmap.put(Integer.valueOf(976), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NP");
        hashmap.put(Integer.valueOf(977), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(979), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TJ");
        hashmap.put(Integer.valueOf(992), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TM");
        hashmap.put(Integer.valueOf(993), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AZ");
        hashmap.put(Integer.valueOf(994), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GE");
        hashmap.put(Integer.valueOf(995), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KG");
        hashmap.put(Integer.valueOf(996), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UZ");
        hashmap.put(Integer.valueOf(998), arraylist);
        return hashmap;
    }

    private PhoneNumber createPhoneNumber(Map map)
    {
        String s = simManager.getCountryIso();
        map = getCountryCode(s, map);
        return new PhoneNumber(stripCountryCode(simManager.getRawPhoneNumber(), map), s, map);
    }

    private String getCountryCode(String s, Map map)
    {
        if (s == null)
        {
            return "";
        }
        s = (Integer)map.get(s.toUpperCase(Locale.getDefault()));
        if (s == null)
        {
            return "";
        } else
        {
            return s.toString();
        }
    }

    private String stripCountryCode(String s, String s1)
    {
        return s.replaceFirst((new StringBuilder("^\\+?")).append(s1).toString(), "");
    }

    protected PhoneNumber getPhoneNumber()
    {
        if (simManager == null)
        {
            return PhoneNumber.emptyPhone();
        } else
        {
            return createPhoneNumber(createCountryCodeByIsoMap());
        }
    }

    protected PhoneNumber getPhoneNumber(String s)
    {
        if (TextUtils.isEmpty(s))
        {
            return getPhoneNumber();
        }
        String s1 = "1";
        String s2 = "US";
        Object obj = s;
        if (s.startsWith("+"))
        {
            obj = createCountryCodeToRegionCodeMap();
            s1 = countryCodeForPhoneNumber(((Map) (obj)), s);
            s2 = countryIsoForCountryCode(((Map) (obj)), s1);
            obj = stripCountryCode(s, s1);
        }
        return new PhoneNumber(((String) (obj)), s2, s1);
    }
}
